go_import_path: bramp.net/dsector
language: go
sudo: false

env:
  - LOGLEVEL=info

# Earlier than 1.7 are not supported
go:
  - 1.7
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
